TIME_OFFSET = 0
BOT_TOKEN = "EXAMPLE_BOT_TOKEN1231"
MAIN_ADMINS = [1234, 4567]
DB_CONNECT_LINK = "mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=false"
BOT_USERNAME = "EXAMPLE_BOTUSERNAME"
CONFIGURATEDB_COMMAND = "fF8xFAKoq25AgNWTe7My"